-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS práva
(
    id serial,
    názov VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS typy_chýb
(
    id serial,
    popis VARCHAR(256)
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS použivatelia
(
    id serial,
    meno VARCHAR(256) NOT NULL,
    priezvisko VARCHAR(256)NOT NULL,
    e-mail VARCHAR(256) NOT NULL,
    heslo VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS zariadenia
(
    id serial,
    nazov_revizie VARCHAR(256) NOT NULL,
    dátum_poslednej_revízie date NOT NULL,
    exspirácia interval NOT NULL,
    dátum_nadchádzajúcej_revízie date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS má_použivateľ_právo
(
    id serial,
    id_používateľa integer NOT NULL,
    id_práva integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS záznamy
(
    id serial,
    id_miesto_na_linke integer NOT NULL,
    id_druh_chyby integer NOT NULL,
    čas_vzniku time without time zone NOT NULL,
    dátum_vzniku date NOT NULL,
    id_použivateľa integer NOT NULL,
    schválená boolean NOT NULL,
    vyriešená boolean NOT NULL,
    čas_vyriešenia time without time zone NOT NULL,
    dátum_vyriešenia date NOT NULL,
    id_spôsobená_kým integer NOT NULL,
    id_typ_chyby integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS druh_chyby
(
    id serial,
    nazov VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sposobena_kym
(
    id serial,
    kym VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS miesto_na_linke
(
    id serial,
    miesto VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS má_použivateľ_právo
    ADD FOREIGN KEY id_používateľa
    REFERENCES použivatelia(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE ;


ALTER TABLE IF EXISTS má_použivateľ_právo
    ADD FOREIGN KEY id_práva
    REFERENCES práva(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE ;


ALTER TABLE IF EXISTS záznamy
    ADD FOREIGN KEY id_použivateľa
    REFERENCES použivatelia(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE ;


ALTER TABLE IF EXISTS záznamy
    ADD FOREIGN KEY (id_typ_chyby)
    REFERENCES typy_chýb (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE ;


ALTER TABLE IF EXISTS záznamy
    ADD FOREIGN KEY (id_druh_chyby)
    REFERENCES druh_chyby (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE ;


ALTER TABLE IF EXISTS záznamy
    ADD FOREIGN KEY id_spôsobená_kým
    REFERENCES sposobena_kym (id) M
    ON UPDATE CASCADE
    ON DELETE CASCADE


ALTER TABLE IF EXISTS záznamy
    ADD FOREIGN KEY (id_miesto_na_linke)
    REFERENCES miesto_na_linke (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE

END;